pipeline {
    agent any
    environment {
        TERRAFORM_CMD = 'terraform'
        MODULE_DIR = 'test_uuid'
        GIT_REPO = 'https://github.com/atrakic/tf_blackbox.git'
    }
    stages {
        stage('checkout repo') {
            steps {
              git branch: 'master', url: "${GIT_REPO}"
              sh  """
                    ${TERRAFORM_CMD} version
                    """
            }
        }
        stage('init') {
            steps {
                dir("${MODULE_DIR}"){
                sh  """
                    ${TERRAFORM_CMD} validate -no-color -check-variables=false . 
                    ${TERRAFORM_CMD} init -no-color -backend=true -input=false
                    """
                }
            }
        stage('plan') {
            steps {
                dir("${MODULE_DIR}"){
                sh  """
                    ${TERRAFORM_CMD} plan -no-color -out=tfplan.${BUILD_ID} -input=false 
                    """
                script {
                  timeout(time: 10, unit: 'MINUTES') {
                    input(id: "Apply further", message: "Deploy ${params.project_name}?", ok: 'Deploy')
                  }
                }
            }
          } 
        }
        stage('apply') {
            dir("${MODULE_DIR}"){
            steps {
                sh  """
                  ${TERRAFORM_CMD} apply -lock=false -input=false tfplan.${BUILD_ID}
                  """
            }
          }
        }
      }
    }
}
